name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  generateREADME:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install `Node.js`
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Generate README
        run: npm run build

      if: github.event_name == 'push'
      - name: Commit changes
        run: |
          git config user.name klaufel
          git config user.email klaufel@gmail.com
          git add .
          git commit -m "Update README"
          git push